// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgttrjonobqsxtlriotl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndHRyam9ub2Jxc3h0bHJpb3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0OTEzMjksImV4cCI6MjA1NTA2NzMyOX0.4_ZokG8ITQtIVp4jGaoJeNnUpi8l_6UaYbnRTOmPTl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);